// Innergy FLS v1 instrument — authoritative V1 content from PRD §7.
//
// Open items (PRD §12) that this fixture RESOLVES PENDING RASHMI SIGN-OFF:
//   §12.1  Section A max = 38 (A8 has max 4; A3 has max 4). Bands scaled to 38.
//   §12.2  Inner Mastery Q8 = "Leadership Presence" variant.
//   §12.3  Inner Mastery bands scaled from 25 → 40.
//   §12.4  Overall bands scaled from 75 → 123 (38 + 45 + 40).
//
// DO NOT ship the Innergy instrument to production until these are confirmed.
// When they are, update only this file + publish a new instrument_version.

import type { InstrumentSpec, OptionLabel } from "../../../core/scoring/types";

// Stable IDs — shared by seeder and tests. These strings are the DB IDs too,
// not autogenerated cuids, so we can rerun seeds idempotently.

export const DIM_COGNITIVE = "dim_cognitive_clarity";
export const DIM_RELATIONAL = "dim_relational_influence";
export const DIM_INNER = "dim_inner_mastery";

export const INSTRUMENT_ID = "inst_innergy_fls";
export const INSTRUMENT_VERSION_ID = "instv_innergy_fls_v1";

// -------------------------------------------------------------------------
// Questions + option text + scores
// -------------------------------------------------------------------------

interface SeedQuestion {
  id: string;
  sectionId: string;
  stem: string;
  displayOrder: number;
  internalTag?: string;
  options: ReadonlyArray<{
    label: OptionLabel;
    text: string;
    score: number;
    displayOrder: number;
  }>;
}

function opts(...scores: [number, number, number, number]): ReadonlyArray<{
  label: OptionLabel;
  text: string;
  score: number;
  displayOrder: number;
}> {
  // Placeholder text is overridden by each question below.
  return (["A", "B", "C", "D"] as const).map((label, i) => ({
    label,
    text: "",
    score: scores[i]!,
    displayOrder: i + 1,
  }));
}

function attachText(
  base: ReadonlyArray<{ label: OptionLabel; score: number; displayOrder: number; text: string }>,
  texts: [string, string, string, string],
) {
  return base.map((o, i) => ({ ...o, text: texts[i]! }));
}

// Section A — Cognitive Clarity (8 Qs, max 38 — see note on A3/A8 at top of file)

const SECTION_A = "sec_cognitive";
const SECTION_B = "sec_relational";
const SECTION_C = "sec_inner";

const A_QUESTIONS: SeedQuestion[] = [
  {
    id: "q_a1",
    sectionId: SECTION_A,
    displayOrder: 1,
    stem: "When I have to make an important decision but don't have all the information I need, I typically:",
    options: attachText(opts(2, 4, 2, 5), [
      "Wait to see if more information emerges to get clarity before committing",
      "Actively find more data to see the full picture",
      "Involve team, ask others or escalate upwards",
      "Push forward with what I know and adjust as I go",
    ]),
  },
  {
    id: "q_a2",
    sectionId: SECTION_A,
    displayOrder: 2,
    stem: "When something urgent lands on my desk — a complaint, a request, a crisis — my first instinct is to:",
    options: attachText(opts(2, 1, 3, 5), [
      "Take control, deal with it immediately so it's off my plate",
      "Figure out how & why this situation occurred in the first place",
      "Delegate it and check back later",
      "Pause & see whether it really needs attention and then decide what to do",
    ]),
  },
  {
    id: "q_a3",
    sectionId: SECTION_A,
    displayOrder: 3,
    stem: "When a decision I made stops producing the results I expected, what below is most representative of you?",
    options: attachText(opts(4, 2, 3, 1), [
      "I find it hard to announce to team that the approach isn't working but eventually I do",
      "It is difficult to figure out what the new plan should be",
      "It is hard to move fast enough to course-correct before too much damage is done",
      "I continue with the plan, sometimes success is just around the corner and does not need a change of direction",
    ]),
  },
  {
    id: "q_a4",
    sectionId: SECTION_A,
    displayOrder: 4,
    stem: "When someone presents a point of view which challenges my beliefs, I most often:",
    options: attachText(opts(4, 5, 2, 1), [
      "Ask lot of questions to understand the veracity of data",
      "Update my view if the evidence is strong enough",
      "Feel defensive initially but come around eventually",
      "Depends entirely on who is challenging it",
    ]),
  },
  {
    id: "q_a5",
    sectionId: SECTION_A,
    displayOrder: 5,
    stem: "If I look at how I spend my thinking time in the last month, most of it went toward:",
    options: attachText(opts(1, 2, 3, 5), [
      "Problems and fires that needed immediate resolution",
      "Delivering on commitments I already made and need delivery within 1 year",
      "Planning and preparing for the next 1–2 years",
      "Thinking about where the industry and business are going in 3–5 years",
    ]),
  },
  {
    id: "q_a6",
    sectionId: SECTION_A,
    displayOrder: 6,
    stem: "When I read about a trend, a technology, or a shift happening in my or another industry, my usual reaction is:",
    options: attachText(opts(3, 2, 5, 4), [
      "I wonder if this could affect us and how",
      "I file it away mentally to act on later",
      "I actively explore whether there is something here for us",
      "I share it with my team to get their perspective",
    ]),
  },
  {
    id: "q_a7",
    sectionId: SECTION_A,
    displayOrder: 7,
    stem: "When something genuinely unexpected happens — a market shift, a competitive move, an internal crisis — my first internal response is usually:",
    options: attachText(opts(2, 5, 3, 2), [
      "Concern about what this means for my existing plans",
      "Curiosity about what this means and what it opens up for me",
      "A need to understand it fully before reacting",
      "An instinct to protect & double down on what is working right now",
    ]),
  },
  {
    id: "q_a8",
    sectionId: SECTION_A,
    displayOrder: 8,
    stem: "How quickly do you recognize emerging technological and market shifts before they impact your company or functional strategy?",
    options: attachText(opts(1, 2, 3, 4), [
      "We get to know once it's already impacted us",
      "We know and can spot 6–12 months in advance",
      "We know and can spot 2–3 years in advance",
      "We are looking at weak signals and working on a long-term strategy",
    ]),
  },
];

// Section B — Relational Influence (9 Qs, max 45)

const B_QUESTIONS: SeedQuestion[] = [
  {
    id: "q_b1",
    sectionId: SECTION_B,
    displayOrder: 1,
    internalTag: "Decision Alignment",
    stem: "When my team makes a decision…",
    options: attachText(opts(1, 2, 4, 5), [
      "People comply but may not always fully commit",
      "Some decisions get team alignment, but not others — depends on how controversial it is",
      "We can consistently converge on a single priority quickly to execute",
      "People execute because they genuinely believe in it and not just because it was decided at the top",
    ]),
  },
  {
    id: "q_b2",
    sectionId: SECTION_B,
    displayOrder: 2,
    internalTag: "Decision Alignment",
    stem: "When my team is pulled in different directions or facing a complex situation where answer is not clear:",
    options: attachText(opts(1, 2, 4, 5), [
      "We struggle — complexity often leads to confusion or paralysis at the team level",
      "We eventually align but it takes longer than it should and creates friction",
      "We align reasonably well — someone usually steps up to create clarity",
      "We find a way to simplify and align — even when we don't have all the answers",
    ]),
  },
  {
    id: "q_b3",
    sectionId: SECTION_B,
    displayOrder: 3,
    internalTag: "Safety",
    stem: "In my team, how do we treat bad news?",
    options: attachText(opts(1, 2, 4, 5), [
      "Bad news is raised late. By the time we hear it, it is already an established problem",
      "It depends on the person",
      "Bad news travels up fairly quickly but there are still blind spots we discover late",
      "Problems surface early consistently — people feel safe raising things before they are certain",
    ]),
  },
  {
    id: "q_b4",
    sectionId: SECTION_B,
    displayOrder: 4,
    internalTag: "Accountability",
    stem: "In our team, how do we give feedback?",
    options: attachText(opts(1, 2, 3, 5), [
      "Feedback is process based, people avoid difficult conversations to keep the peace",
      "Feedback happens but it is often softened to the point where the message gets lost",
      "Feedback is generally direct but occasionally becomes personal or creates defensiveness",
      "Feedback is frequent, clear, and the team receives it well without taking it personally",
    ]),
  },
  {
    id: "q_b5",
    sectionId: SECTION_B,
    displayOrder: 5,
    internalTag: "Cross-functional Influence",
    stem: "How does my team operate while working with people with varying levels of experience, personalities and diverse functions and cultures?",
    options: attachText(opts(1, 2, 4, 5), [
      "We experience frequent friction and conflict when working across different teams or cultures and it slows us down",
      "We work well within our own team but friction and misalignment tend to surface when we engage across other teams or cultures",
      "We generally work well across differences but occasional friction or conflict still surfaces",
      "We navigate differences in generation, function, and culture with low friction",
    ]),
  },
  {
    id: "q_b6",
    sectionId: SECTION_B,
    displayOrder: 6,
    internalTag: "Responsiveness",
    stem: "When a strategic decision is made, how quickly does our team's operations and execution shift to reflect it?",
    options: attachText(opts(1, 2, 4, 5), [
      "Slowly — it takes significant time before the decision is visible in how we actually work",
      "Moderately — we shift eventually but there is always a gap between decision and action",
      "Quickly in most cases — the team generally moves fast when direction is clear",
      "Very quickly — once a decision is made the team realigns operations almost immediately",
    ]),
  },
  {
    id: "q_b7",
    sectionId: SECTION_B,
    displayOrder: 7,
    internalTag: "Resource Calibration",
    stem: "When a new priority emerges, how is that treated by our team?",
    options: attachText(opts(1, 2, 4, 5), [
      "We rarely reallocate — existing commitments and budgets tend to stay intact even when priorities shift",
      "We reallocate partially — some resources shift but there is significant resistance to letting go",
      "We reallocate meaningfully in most cases",
      "We reallocate visibly & decisively — when a new priority is clear the team moves budget, talent and focus",
    ]),
  },
  {
    id: "q_b8",
    sectionId: SECTION_B,
    displayOrder: 8,
    internalTag: "Resource Calibration",
    stem: "When a project or initiative is no longer aligned with where we are going, what do we do?",
    options: attachText(opts(1, 2, 4, 5), [
      "We rarely shut things down, projects tend to continue long after they should have stopped",
      "We sometimes shut things down but it is slow and politically difficult",
      "We generally shut things down when it is amply clear they are no longer working",
      "We shut things down quickly and without drama when they no longer serve where we are going",
    ]),
  },
  {
    id: "q_b9",
    sectionId: SECTION_B,
    displayOrder: 9,
    internalTag: "Signal Sensing",
    stem: 'How frequently do we actively prioritize spotting external "weak signals" to shape our team\'s strategic discussions?',
    options: attachText(opts(1, 2, 4, 5), [
      "We seek more information to check whether it is the correct read of the market",
      "We test quickly & learn",
      "We put the finding through our risk management process and make a business case",
      "We trust the team who came up with signal and get into action",
    ]),
  },
];

// Section C — Inner Mastery (8 Qs, max 40; Q8 = "Leadership Presence" variant)

const C_QUESTIONS: SeedQuestion[] = [
  {
    id: "q_c1",
    sectionId: SECTION_C,
    displayOrder: 1,
    internalTag: "Nervous system regulation under pressure",
    stem: "When I am in a high-stakes situation — a crisis, a difficult conversation, a major decision under time pressure — my thinking & judgement:",
    options: attachText(opts(1, 2, 4, 5), [
      "Becomes scattered",
      "Focus narrows, I could miss wider context",
      "Stays clear — pressure doesn't significantly affect my thinking",
      "Sharpens — high-stakes situations bring out my clearest thinking",
    ]),
  },
  {
    id: "q_c2",
    sectionId: SECTION_C,
    displayOrder: 2,
    internalTag: "Decision Making Under Pressure",
    stem: "Under a long period of stressful work, my decision-making:",
    options: attachText(opts(1, 2, 4, 5), [
      "I get into fire-fighting mode, more reactive, delay complex decisions",
      "I become more cautious & risk averse",
      "I stay consistent — I maintain decision quality",
      "I remain reliable — I have the tools to maintain clarity",
    ]),
  },
  {
    id: "q_c3",
    sectionId: SECTION_C,
    displayOrder: 3,
    internalTag: "Emotional Stability",
    stem: "When people around me are anxious, stressed, or in conflict, I notice my own inner state:",
    options: attachText(opts(1, 2, 4, 5), [
      "I absorb the emotional atmosphere and it affects my thoughts and productivity",
      "I feel the pull but try to maintain my workflow — it takes effort",
      "I can feel the tension without it significantly altering my productivity",
      "It does not affect me; sometimes I have a positive effect by reducing tension",
    ]),
  },
  {
    id: "q_c4",
    sectionId: SECTION_C,
    displayOrder: 4,
    internalTag: "Recovery and Reflection",
    stem: "After a hard period — a setback, sustained pressure, major conflict — I recover by:",
    options: attachText(opts(1, 3, 3, 5), [
      "Not able to afford recovery time; I snap back and carry it into subsequent situations",
      "Recover eventually but it takes more time and deliberate effort",
      "I recover with some effort and also carve out time to introspect",
      "I recover relatively quickly because I have built practices that help me process and reset",
    ]),
  },
  {
    id: "q_c5",
    sectionId: SECTION_C,
    displayOrder: 5,
    internalTag: "Rest and Restoration",
    stem: "When I step away from work — evenings, weekends, holidays — I:",
    options: attachText(opts(1, 2, 4, 5), [
      "Don't switch off / find it difficult to switch off",
      "Can stop working but don't fully feel rested",
      "Generally able to disconnect and rest reasonably well",
      "Meaningfully disconnect and return more energised than before",
    ]),
  },
  {
    id: "q_c6",
    sectionId: SECTION_C,
    displayOrder: 6,
    internalTag: "Purpose",
    stem: "When I reflect on why I lead — the deeper reason beyond the role or results — I find that:",
    options: attachText(opts(1, 2, 4, 5), [
      "I don't often think about this",
      "I have a sense of it but it changes depending on circumstances",
      "I have a clear enough sense and it helps me stay oriented — especially when things get hard",
      "My sense of purpose is what I return to when everything else is uncertain",
    ]),
  },
  {
    id: "q_c7",
    sectionId: SECTION_C,
    displayOrder: 7,
    internalTag: "Whole Brain Access",
    stem: "When I need to make a judgment call that goes beyond what the data can tell me:",
    options: attachText(opts(1, 2, 4, 5), [
      "I struggle without clear data — I delay, defer, or default to what has worked before",
      "I can make the call but don't fully trust it",
      "I generally trust my judgment in these moments",
      "I am certain in moments which could be technically overwhelming; my clearest thinking often happens in these moments",
    ]),
  },
  {
    id: "q_c8",
    sectionId: SECTION_C,
    displayOrder: 8,
    internalTag: "Leadership Presence",
    stem: "When I think about the effect my presence has on the people around me — my energy, my mood, my level of stress — I would say:",
    options: attachText(opts(1, 2, 4, 5), [
      "I am honestly not very aware of it",
      "I am aware when someone points it out or when I notice a visible reaction — but I don't track it proactively",
      "I am generally aware and make a conscious effort to manage it, especially in high-stakes situations",
      "I have a clear and continuous sense of the energy I am bringing and actively work to ensure my presence is a resource rather than a drain",
    ]),
  },
];

// -------------------------------------------------------------------------
// Bands (PRD §7)
// -------------------------------------------------------------------------

export const SECTION_A_BANDS = [
  { minScore: 31, maxScore: 38, bandLabel: "Strong", colorHex: "#16a34a",
    interpretationTemplate:
      "Genuine cognitive agility. Filters well, adapts fast, thinks ahead, stays curious under pressure." },
  { minScore: 23, maxScore: 30, bandLabel: "Developing", colorHex: "#eab308",
    interpretationTemplate:
      "Real capability present but inconsistent. Thinks clearly in familiar territory, struggles when situations are genuinely new." },
  { minScore: 14, maxScore: 22, bandLabel: "At Risk", colorHex: "#f97316",
    interpretationTemplate:
      "Predominantly reactive and backward-looking. Will be increasingly exposed as the pace of change accelerates." },
  { minScore: 8,  maxScore: 13, bandLabel: "Critical Gap", colorHex: "#dc2626",
    interpretationTemplate:
      "The cognitive infrastructure for leading in complexity is not yet built. Significant and urgent intervention needed." },
];

export const SECTION_B_BANDS = [
  { minScore: 33, maxScore: 45, bandLabel: "Strong", colorHex: "#16a34a",
    interpretationTemplate:
      "This team operates with genuine relational maturity. Decisions land, feedback flows, execution is fast, and the team can let go when needed." },
  { minScore: 24, maxScore: 32, bandLabel: "Developing", colorHex: "#eab308",
    interpretationTemplate:
      "Real relational capability exists but is inconsistent. Performs well in familiar conditions, shows friction under complexity or diversity." },
  { minScore: 15, maxScore: 23, bandLabel: "At Risk", colorHex: "#f97316",
    interpretationTemplate:
      "The team's relational dynamics are limiting execution and adaptability. Compliance is mistaken for alignment." },
  { minScore: 9,  maxScore: 14, bandLabel: "Critical Gap", colorHex: "#dc2626",
    interpretationTemplate:
      "The team is operating on relational patterns built for a slower, more stable world. Gaps are cultural and require structural intervention." },
];

export const SECTION_C_BANDS = [
  { minScore: 32, maxScore: 40, bandLabel: "Strong", colorHex: "#16a34a",
    interpretationTemplate:
      "This dimension is a genuine asset in your leadership. The foundation is there. The work now is to extend it, protect it under pressure, and scale it as the organisation grows." },
  { minScore: 22, maxScore: 31, bandLabel: "Developing", colorHex: "#eab308",
    interpretationTemplate:
      "Capability exists but is inconsistent. Some situations bring it out, others expose the gap. Targeted investment will create disproportionate return." },
  { minScore: 12, maxScore: 21, bandLabel: "At Risk", colorHex: "#f97316",
    interpretationTemplate:
      "A quiet liability — not visible in stable conditions, but under pressure or during change, it shows up as a constraint on performance." },
  { minScore: 8,  maxScore: 11, bandLabel: "Critical Gap", colorHex: "#dc2626",
    interpretationTemplate:
      "Not a development priority — a business risk. Leaders operating here are actively limiting the people around them." },
];

export const OVERALL_BANDS = [
  { minScore: 98, maxScore: 123, bandLabel: "AI-Ready",
    interpretationTemplate:
      "Your leadership has the foundation to thrive in the AI age. The priority now is staying ahead — building the practices that keep this edge as the pace accelerates." },
  { minScore: 72, maxScore: 97, bandLabel: "Partially Ready",
    interpretationTemplate:
      "Real strengths with meaningful gaps. In stable conditions this works. As AI raises the bar on speed, judgment, and adaptability, these gaps will become more visible and more costly." },
  { minScore: 48, maxScore: 71, bandLabel: "At Risk (Developing Readiness)",
    interpretationTemplate:
      "Operating on a model built for a slower world. Gaps across one or more dimensions are significant enough that they are likely already affecting execution, culture, and retention." },
  { minScore: 24, maxScore: 47, bandLabel: "Critical (High Risk)",
    interpretationTemplate:
      "The leadership infrastructure is not fit for what is coming. Needs a fundamental reset, not another training programme." },
];

// -------------------------------------------------------------------------
// Exported fixture + pure-spec builder for the scoring engine
// -------------------------------------------------------------------------

export const INNERGY_V1_SECTIONS = [
  {
    id: SECTION_A,
    dimensionId: DIM_COGNITIVE,
    displayOrder: 1,
    introTemplateKey: "section_intro_cognitive",
    questions: A_QUESTIONS,
  },
  {
    id: SECTION_B,
    dimensionId: DIM_RELATIONAL,
    displayOrder: 2,
    introTemplateKey: "section_intro_relational",
    questions: B_QUESTIONS,
  },
  {
    id: SECTION_C,
    dimensionId: DIM_INNER,
    displayOrder: 3,
    introTemplateKey: "section_intro_inner",
    questions: C_QUESTIONS,
  },
] as const;

export function buildInnergyV1Spec(): InstrumentSpec {
  const dimensionBands = [
    ...SECTION_A_BANDS.map((b) => ({ ...b, dimensionId: DIM_COGNITIVE })),
    ...SECTION_B_BANDS.map((b) => ({ ...b, dimensionId: DIM_RELATIONAL })),
    ...SECTION_C_BANDS.map((b) => ({ ...b, dimensionId: DIM_INNER })),
  ];

  return {
    instrumentVersionId: INSTRUMENT_VERSION_ID,
    sections: INNERGY_V1_SECTIONS.map((s) => ({
      id: s.id,
      dimensionId: s.dimensionId,
      displayOrder: s.displayOrder,
      questions: s.questions.map((q) => ({
        id: q.id,
        sectionId: q.sectionId,
        options: q.options.map((o) => ({ label: o.label, score: o.score })),
      })),
    })),
    dimensionBands,
    overallBands: OVERALL_BANDS,
  };
}
